### ISSUE TITLE
No icons... (Firefox-ESR-45.3.0 / Debian-8.5)

### ISSUE THREAD

**Issue by drawkula** [moononournation/nodemcu-webide#3]
nodemcu-webide doesn't display icons in Firefox-ESR-45.3.0 (on Debian-8.5).

With "Chromium Version 52.0.2743.116 Built on 8.5, running on Debian 8.5 (64-bit)" everything looks fine...

(Still running [the old firmware](https://github.com/moononournation/nodemcu-webide/commit/91d3e4fbfccc41bf20f64c04f64c9f6caf478dfc) because [the newer one](https://github.com/moononournation/nodemcu-webide/commit/ef89c3e8622783fe2f879089e8b8644e487fe75c) does a crash & <strike>hexdump</strike> print loop here (on "Amica"), but that'll be a different issue when cross checked against other nodemcu-boards.)

**Comment by moononournation** [comment]
I have changed all inline SVG images from plain text to base64 encoding. The index.html is now a little bit bigger but improved browser compatibility.
You may now test it again.

**Comment by drawkula** [comment]
On several tries I only get "404 - Not Found" with the new flash image.

But I had an allergic shock yesterday and am still full of antihistamines today and feel they slowing me down... so today I may be the the problem here.

I'll retry tomorrow. The impact of Sunday's infusions should be gone then.

Meanwhile some other Firefox users can be faster than me and test it?

**Comment by moononournation** [comment]
seems spiffs have lost some files again, I will wirte another image tonight.

yeti notifications@github.com 於 2016年8月23日星期二 寫道：

**Comment by drawkula** [comment]
I uploaded all files via `nodemcu-uploader` and most stuff seems to be ok, especially editing and saving.

I noticed 2 things but I could only test for some minutes up to now.
My testing sure was not exhaustive.
1. The file list does not automatically reload after changes like creating a new file. A browser reload command is needed.
2. The icon line above the file list is not tall enough. It's not unreadable... this is not urgent.

Icons are visible now, all other aspects may be own independent issues if you wish...

**Comment by moononournation** [comment]
1. updated some Javascript to improve browser compatibility
2. increased toolbar height from 20px to 24px

**Comment by drawkula** [comment]
I flashed [the new image](https://github.com/moononournation/nodemcu-webide/commit/6091d2e12007130b5a70afe8ff58f2287f35b7fb) onto a NodeMCU-Devkit-0.9 board and after restart I only see trash on the serial port.

Restart...
- flashed the oldest image
- formated the file system
- uploaded all files from `bin` folder using `nodemcu-upoader`
- configured `config.lua` to match my WLAN settings using `ESPlorer`
- created and edited `node.restart.lua` as test file...

Result...

![20160824-152325-gmt - nodemcu webide on ff-esr-45 3 0](https://cloud.githubusercontent.com/assets/9768622/17936634/be83abf0-6a1f-11e6-9933-50d6b49e992d.png)
(Snapshot from `Firefox-ESR-45.3.0 / Debian-8.5`)

10000 thanks!
;-)

**Comment by moononournation** [comment]
seems ok now
