### ISSUE TITLE
What is wifi password

### ISSUE THREAD

**Issue by ashishagravat** [moononournation/nodemcu-webide#4]
hey 
im flash your crated webide file .
and esp now on show is MicroPython-376ce3 wifi but its password protected so what is the password ??

**Comment by drawkula** [comment]
Look there: https://github.com/moononournation/nodemcu-webide/blob/master/bin/config.lua#L12-L13

**Comment by ashishagravat** [comment]
hey @drawkula 
thanks for reply

can you please explain p step by step full process of webide

what iam doing now
1)flash nodemcu-webide.bin file using nodemcu flash downlorder tool
than flash custom build firmware  using" http://nodemcu-build.com "
than open esplorer and send config.lua 

now what is nexstep can you please tell me.
